crczp-elasticsearch:
  pvc:
    storageClassName: gp3

crczp-guacamole:
  guacd:
    pvc:
      storageClassName: gp3

postgres:
  pvc:
    storageClassName: gp3

sandbox:
  manUser: ubuntu
  stackNamePrefix: default
  osConsoleType: spice-html5
  dnsNameServers:
    - 1.1.1.1
    - 1.0.0.1
  pvc:
    enabled: true
    storageClassName: root-efs-sc
    accessMode: ReadWriteMany
